--Cloning a transient schema within the same database--
CREATE TRANSIENT SCHEMA MY_FIRST_DB.COPIED_SCHEMA
CLONE MY_FIRST_DB.PUBLIC;
--Display the copies-schema table--
SELECT * FROM COPIED_SCHEMA.CUSTOMERS;
--Cloning a transient schema in different database--
CREATE TRANSIENT SCHEMA MY_FIRST_DB.EXTERNAL_STAGES_COPIED
CLONE STAGING_DB.EXTERNAL_STAGES;
--Cloning Database
CREATE TRANSIENT DATABASE MY_FIRST_DB_COPY
CLONE MY_FIRST_DB;
--Drop all the schemas and database--
DROP DATABASE MY_FIRST_DB_COPY;
DROP SCHEMA MY_FIRST_DB.EXTERNAL_STAGES_COPIED;
DROP SCHEMA MY_FIRST_DB.COPIED_SCHEMA;
