SHOW SHARES;
--Create share object--
CREATE OR REPLACE SHARE COMEPLETE_SCHEMA_SHARE;
--Grant usage on dabase & schema--
GRANT USAGE ON DATABASE OUR_FIRST_DB TO SHARE COMEPLETE_SCHEMA_SHARE;
GRANT USAGE ON SCHEMA OUR_FIRST_DB.PUBLIC TO SHARE COMEPLETE_SCHEMA_SHARE;
--Grant select on all tables--
GRANT SELECT ON ALL TABLES IN SCHEMA OUR_FIRST_DB.PUBLIC TO SHARE COMEPLETE_SCHEMA_SHARE;
GRANT SELECT ON ALL TABLES IN DATABASE OUR_FIRST_DB TO SHARE COMEPLETE_SCHEMA_SHARE;
--Add account to share--
ALTER SHARE COMEPLETE_SCHEMA_SHARE
ADD ACCOUNT=DF48575;

--Commands to be given in consumer account--
show shares;
--See details on share--
DESC SHARE BZLOQAF.RC57230.COMEPLETE_SCHEMA_SHARE;
--Create a database in consumer account using the share--
CREATE DATABASE OUR_FIRST_DB FROM SHARE BZLOQAF.RC57230.COMEPLETE_SCHEMA_SHARE;
--Validate table access--
SELECT * FROM OUR_FIRST_DB.PUBLIC.ORDERS;

--Commands in this producer account--
--Updating data--
UPDATE OUR_FIRST_DB.PUBLIC.ORDERS
SET PROFIT=0 WHERE PROFIT < 0;
--Add new table--
CREATE TABLE OUR_FIRST_DB.PUBLIC.NEW_TABLE (ID int);
