--Creating a secure view and joining two DB's--
CREATE OR REPLACE SECURE VIEW SECURE_VIEW_M AS
SELECT 
T1.ID, 
T1.FIRST_NAME,
T2.JOB
FROM CUSTOMER_DB.PUBLIC.CUSTOMERS T1
INNER JOIN  MY_FIRST_DB.PUBLIC.CUSTOMERS T2
ON T1.ID = T2.ID;
--Display the view(Keep the database to customer_db)--
SELECT * FROM SECURE_VIEW_M;

SHOW SHARES;
--Create share object--
CREATE OR REPLACE SHARE VIEW_SHARE;
--Grant usage on dabase & schema--
GRANT USAGE ON DATABASE CUSTOMER_DB TO SHARE VIEW_SHARE;
GRANT USAGE ON SCHEMA CUSTOMER_DB.PUBLIC TO SHARE VIEW_SHARE;
GRANT REFERENCE_USAGE ON DATABASE MY_FIRST_DB TO SHARE VIEW_SHARE;
--Grant select on view--
GRANT SELECT ON VIEW  CUSTOMER_DB.PUBLIC.SECURE_VIEW_M TO SHARE VIEW_SHARE;
GRANT SELECT ON VIEW  CUSTOMER_DB.PUBLIC.CUSTOMER_VIEW_SECURE TO SHARE VIEW_SHARE;

alter share VIEW_SHARE
set secure_objects_only = false;
--Add account to share--
ALTER SHARE VIEW_SHARE
ADD ACCOUNT=DF48575;

--Commands to be given on consumer account--
show shares;
DESC SHARE BZLOQAF.RC57230.VIEW_SHARE;
CREATE DATABASE VIEW_DB_M FROM SHARE BZLOQAF.RC57230.VIEW_SHARE;
SELECT * FROM VIEW_DB_M.PUBLIC.CUSTOMER_VIEW_SECURE;
