SHOW SHARES;
--Create share object--
CREATE OR REPLACE SHARE VIEW_SHARE;
--Grant usage on dabase & schema--
GRANT USAGE ON DATABASE CUSTOMER_DB TO SHARE VIEW_SHARE;
GRANT USAGE ON SCHEMA CUSTOMER_DB.PUBLIC TO SHARE VIEW_SHARE;
--Allow non-secure objects in share--
ALTER SHARE VIEW_SHARE SET SECURE_OBJECTS_ONLY = FALSE;
--Grant select on view--
GRANT SELECT ON VIEW  CUSTOMER_DB.PUBLIC.CUSTOMER_VIEW TO SHARE VIEW_SHARE;
GRANT SELECT ON VIEW  CUSTOMER_DB.PUBLIC.CUSTOMER_VIEW_SECURE TO SHARE VIEW_SHARE;
--Add account to share--
ALTER SHARE VIEW_SHARE
ADD ACCOUNT=DF48575;

--Commands to be given in consumer account--
show shares;
--See details on share--
DESC SHARE BZLOQAF.RC57230.VIEW_SHARE;
--Create a database in consumer account using the share--
CREATE DATABASE VIEW_DB FROM SHARE BZLOQAF.RC57230. VIEW_SHARE;
--Validate table access--
SELECT * FROM VIEW_DB.PUBLIC.CUSTOMER_VIEW_SECURE;