--Setting up dev table--
CREATE TRANSIENT SCHEMA MY_FIRST_DB.COPIED_SCHEMA
CLONE MY_FIRST_DB.PUBLIC;

SELECT * FROM MY_FIRST_DB.COPIED_SCHEMA.CUSTOMERS
SELECT * FROM MY_FIRST_DB.PUBLIC.CUSTOMERS;

--Modifying "Dev Table"--
DELETE FROM MY_FIRST_DB.COPIED_SCHEMA.CUSTOMERS WHERE ID < 500;

SELECT * FROM MY_FIRST_DB.COPIED_SCHEMA.CUSTOMERS;

--Swapping Tables--
ALTER TABLE MY_FIRST_DB.COPIED_SCHEMA.CUSTOMERS
SWAP WITH MY_FIRST_DB.PUBLIC.CUSTOMERS;

--Verifying results
SELECT * FROM MY_FIRST_DB.COPIED_SCHEMA.CUSTOMERS;
SELECT * FROM MY_FIRST_DB.PUBLIC.CUSTOMERS;