USE TASK_DB;
 
SHOW TASKS;

SELECT * FROM CUSTOMERS;

--Prepare a second table--
CREATE OR REPLACE TABLE CUSTOMERS2 (
    CUSTOMER_ID INT,
    FIRST_NAME VARCHAR(40),
    CREATE_DATE DATE);   
--Suspend parent task--
ALTER TASK CUSTOMER_INSERT SUSPEND;
--Create a child task--
CREATE OR REPLACE TASK CUSTOMER_INSERT2
    WAREHOUSE = COMPUTE_WH
    AFTER CUSTOMER_INSERT
    AS 
    INSERT INTO CUSTOMERS2 SELECT * FROM CUSTOMERS;
--Prepare a third table--
CREATE OR REPLACE TABLE CUSTOMERS3 (
    CUSTOMER_ID INT,
    FIRST_NAME VARCHAR(40),
    CREATE_DATE DATE,
    INSERT_DATE DATE DEFAULT DATE(CURRENT_TIMESTAMP));    
--Create a child task--
CREATE OR REPLACE TASK CUSTOMER_INSERT3
    WAREHOUSE = COMPUTE_WH
    AFTER CUSTOMER_INSERT2
    AS 
    INSERT INTO CUSTOMERS3 (CUSTOMER_ID,FIRST_NAME,CREATE_DATE) SELECT * FROM CUSTOMERS2;
--Show the tasks--
SHOW TASKS;
--Dont try it now. Its already same--
ALTER TASK CUSTOMER_INSERT 
SET SCHEDULE = '1 MINUTE';
--Resume tasks (child task first)--
ALTER TASK CUSTOMER_INSERT2 RESUME;
ALTER TASK CUSTOMER_INSERT3 RESUME;
ALTER TASK CUSTOMER_INSERT RESUME;
--Check the child tables--
SELECT * FROM CUSTOMERS2;
SELECT * FROM CUSTOMERS3;
--Suspend tasks again(Root task first)--
ALTER TASK CUSTOMER_INSERT SUSPEND;
ALTER TASK CUSTOMER_INSERT2 SUSPEND;
ALTER TASK CUSTOMER_INSERT3 SUSPEND;
--Drop the tasks once it is done--
DROP TASK  CUSTOMER_INSERT;
DROP TASK  CUSTOMER_INSERT2;
DROP TASK  CUSTOMER_INSERT3;

